/// @addtogroup phonemeTables
/// @{
///
/// their are 81 phonemes in the SAM. @n
/// they are numberd by 0-80. @n
/// every phoneme has property: id(0-80) name(1-2characters), normal-length, stressed-length, freq123, amp123 consonant-flags
///
///
/// phoneme name has 1-2 characters. the name is stored in
/// @ref phonemeNameTable1 (for first char)  and @ref phonemeNameTable2 (for second char) .@n
/// @ref phonemeLengthTable is the default length of the phoneme. @n
/// @ref phonemeStressedLengthTable is the default stressed length of the phoneme. @n
/// the unit of the length is frame. one frame is approxmitly 10ms. @n
///
/// the phoneme have three types. @n
/// 1. vowel, which is generated by 3-formants. wave=f1wav*f1amp + f2wav*f2amp * f3wav*f3amp @n
/// 2. unvoiced-consonant. which is just recorded and played when need.the data is stored in: wave= @ref consonantSampleTable . @n
/// 3. voiced-consonant. which is wave=1+2. wave=f1wav*f1amp + f2wav*f2amp * f3wav*f3amp + @ref consonantSampleTable @n
///
///
/// @ref freq1data @ref freq2data  @ref freq3data and @ref ampl1data @ref ampl2data @ref ampl3data is the phoneme formant freq and amp.  @n
/// @ref sampledConsonantFlags is the phoneme flag, include the consonantSample pos and consonantSample length.
///
/// @ref https://sites.google.com/site/h2obsession/CBM/C128/SAM-128/phonemes
///
///
///
///
///
///
///
///
///
///



/// phoneme name table
///
///
///
unsigned char phonemeNameTable1[]={
    ' ', '.', '?', ',', '-', 'I', 'I', 'E',
    'A', 'A', 'A', 'A', 'U', 'A', 'I', 'E',
    'U', 'O', 'R', 'L', 'W', 'Y', 'W', 'R',
    'L', 'W', 'Y', 'M', 'N', 'N', 'D', 'Q',
    'S', 'S', 'F', 'T', '/', '/', 'Z', 'Z',
    'V', 'D', 'C', '*', 'J', '*', '*', '*',
    'E', 'A', 'O', 'A', 'O', 'U', 'B', '*',
    '*', 'D', '*', '*', 'G', '*', '*', 'G',
    '*', '*', 'P', '*', '*', 'T', '*', '*',
    'K', '*', '*', 'K', '*', '*', 'U', 'U',
    'U'
};

///
/// PhonemeNameTable2
unsigned char PhonemeNameTable2[] =
{
    '*', '*', '*', '*', '*', 'Y', 'H', 'H',
    'E', 'A', 'H', 'O', 'H', 'X', 'X', 'R',
    'X', 'H', 'X', 'X', 'X', 'X', 'H', '*',
    '*', '*', '*', '*', '*', 'X', 'X', '*',
    '*', 'H', '*', 'H', 'H', 'X', '*', 'H',
    '*', 'H', 'H', '*', '*', '*', '*', '*',
    'Y', 'Y', 'Y', 'W', 'W', 'W', '*', '*',
    '*', '*', '*', '*', '*', '*', '*', 'X',
    '*', '*', '*', '*', '*', '*', '*', '*',
    '*', '*', '*', 'X', '*', '*', 'L', 'M',
    'N'
};

//tab45536???
unsigned char phonemeLengthTable[] =
{
    0 , 0x12 , 0x12 , 0x12 , 8 , 8 , 8 , 8 ,
    8 ,0xB , 6 ,0xC ,0xA , 5 , 5 ,0xB ,
    0xA ,0xA ,0xA , 9 , 8 , 7 , 9 , 7 ,
    6 , 8 , 6 , 7 , 7 , 7 , 2 , 5 ,
    2 , 2 , 2 , 2 , 2 , 2 , 6 , 6 ,
    7 , 6 , 6 , 2 , 8 , 3 , 1 , 0x1E ,
    0xD ,0xC ,0xC ,0xC ,0xE , 9 , 6 , 1 ,
    2 , 5 , 1 , 1 , 6 , 1 , 2 , 6 ,
    1 , 2 , 8 , 2 , 2 , 4 , 2 , 2 ,
    6 , 1 , 4 , 6 , 1 , 4 , 0xC7 , 0xFF
};


//tab45616???
unsigned char phonemeStressedLengthTable[] =
{
    0x00 , 0x12 , 0x12 , 0x12 , 8 ,0xB , 9 ,0xB ,
    0xE ,0xF ,0xB , 0x10 ,0xC , 6 , 6 ,0xE ,
    0xC ,0xE ,0xC ,0xB , 8 , 8 ,0xB ,0xA ,
    9 , 8 , 8 , 8 , 8 , 8 , 3 , 5 ,
    2 , 2 , 2 , 2 , 2 , 2 , 6 , 6 ,
    8 , 6 , 6 , 2 , 9 , 4 , 2 , 1 ,
    0xE ,0xF ,0xF ,0xF ,0xE ,0xE , 8 , 2 ,
    2 , 7 , 2 , 1 , 7 , 2 , 2 , 7 ,
    2 , 2 , 8 , 2 , 2 , 6 , 2 , 2 ,
    7 , 2 , 4 , 7 , 1 , 4 , 5 , 5
};

//tab45056
unsigned char freq1data[]=
{
    0x00 ,0x13 ,0x13 ,0x13 ,0x13 , 0xA , 0xE ,0x12
    ,  0x18 ,0x1A ,0x16 ,0x14 ,0x10 ,0x14 , 0xE ,0x12
    ,	0xE ,0x12 ,0x12 ,0x10 , 0xC , 0xE , 0xA ,0x12
    ,	0xE ,0xA  , 8  , 6  , 6  ,  6 ,  6 ,0x11
    ,	 6 , 6 , 6 , 6 ,0xE , 0x10 , 9 ,0xA
    ,	 8 ,0xA , 6 , 6 , 6 , 5 , 6 , 0
    ,  0x12 , 0x1A , 0x14 , 0x1A , 0x12 ,0xC , 6 , 6
    ,	 6 , 6 , 6 , 6 , 6 , 6 , 6 , 6
    ,	 6 , 6 , 6 , 6 , 6 , 6 , 6 , 6
    ,	 6 ,0xA ,0xA , 6 , 6 , 6 , 0x2C , 0x13
};

//tab451356
unsigned char freq2data[]=
{
    0x00 , 0x43 , 0x43 , 0x43 , 0x43 , 0x54 , 0x48 , 0x42 ,
    0x3E , 0x28 , 0x2C , 0x1E , 0x24 , 0x2C , 0x48 , 0x30 ,
    0x24 , 0x1E , 0x32 , 0x24 , 0x1C , 0x44 , 0x18 , 0x32 ,
    0x1E , 0x18 , 0x52 , 0x2E , 0x36 , 0x56 , 0x36 , 0x43 ,
    0x49 , 0x4F , 0x1A , 0x42 , 0x49 , 0x25 , 0x33 , 0x42 ,
    0x28 , 0x2F , 0x4F , 0x4F , 0x42 , 0x4F , 0x6E , 0x00 ,
    0x48 , 0x26 , 0x1E , 0x2A , 0x1E , 0x22 , 0x1A , 0x1A ,
    0x1A , 0x42 , 0x42 , 0x42 , 0x6E , 0x6E , 0x6E , 0x54 ,
    0x54 , 0x54 , 0x1A , 0x1A , 0x1A , 0x42 , 0x42 , 0x42 ,
    0x6D , 0x56 , 0x6D , 0x54 , 0x54 , 0x54 , 0x7F , 0x7F
};

//tab45216
unsigned char freq3data[]=
{
    0x00 , 0x5B , 0x5B , 0x5B , 0x5B , 0x6E , 0x5D , 0x5B ,
    0x58 , 0x59 , 0x57 , 0x58 , 0x52 , 0x59 , 0x5D , 0x3E ,
    0x52 , 0x58 , 0x3E , 0x6E , 0x50 , 0x5D , 0x5A , 0x3C ,
    0x6E , 0x5A , 0x6E , 0x51 , 0x79 , 0x65 , 0x79 , 0x5B ,
    0x63 , 0x6A , 0x51 , 0x79 , 0x5D , 0x52 , 0x5D , 0x67 ,
    0x4C , 0x5D , 0x65 , 0x65 , 0x79 , 0x65 , 0x79 , 0x00 ,
    0x5A , 0x58 , 0x58 , 0x58 , 0x58 , 0x52 , 0x51 , 0x51 ,
    0x51 , 0x79 , 0x79 , 0x79 , 0x70 , 0x6E , 0x6E , 0x5E ,
    0x5E , 0x5E , 0x51 , 0x51 , 0x51 , 0x79 , 0x79 , 0x79 ,
    0x65 , 0x65 , 0x70 , 0x5E , 0x5E , 0x5E , 0x08 , 0x01
};

unsigned char ampl1data[] =
{
    0 , 0 , 0 , 0 , 0 ,0xD ,0xD ,0xE ,
    0xF ,0xF ,0xF ,0xF ,0xF ,0xC ,0xD ,0xC ,
    0xF ,0xF ,0xD ,0xD ,0xD ,0xE ,0xD ,0xC ,
    0xD ,0xD ,0xD ,0xC , 9 , 9 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 ,0xB ,0xB ,
    0xB ,0xB , 0 , 0 , 1 ,0xB , 0 , 2 ,
    0xE ,0xF ,0xF ,0xF ,0xF ,0xD , 2 , 4 ,
    0 , 2 , 4 , 0 , 1 , 4 , 0 , 1 ,
    4 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 ,0xC , 0 , 0 , 0 , 0 ,0xF ,0xF
};

unsigned char ampl2data[] =
{
    0 , 0 , 0 , 0 , 0 ,0xA ,0xB ,0xD ,
    0xE ,0xD ,0xC ,0xC ,0xB , 9 ,0xB ,0xB ,
    0xC ,0xC ,0xC , 8 , 8 ,0xC , 8 ,0xA ,
    8 , 8 ,0xA , 3 , 9 , 6 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 3 , 5 ,
    3 , 4 , 0 , 0 , 0 , 5 ,0xA , 2 ,
    0xE ,0xD ,0xC ,0xD ,0xC , 8 , 0 , 1 ,
    0 , 0 , 1 , 0 , 0 , 1 , 0 , 0 ,
    1 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 ,0xA , 0 , 0 ,0xA , 0 , 0 , 0
};

unsigned char ampl3data[] =
{
    0 , 0 , 0 , 0 , 0 , 8 , 7 , 8 ,
    8 , 1 , 1 , 0 , 1 , 0 , 7 , 5 ,
    1 , 0 , 6 , 1 , 0 , 7 , 0 , 5 ,
    1 , 0 , 8 , 0 , 0 , 3 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 1 ,
    0 , 0 , 0 , 0 , 0 , 1 ,0xE , 1 ,
    9 , 1 , 0 , 1 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 7 , 0 , 0 , 5 , 0 , 0x13 , 0x10
};






/// High bits masked by 248 (11111000) @n
/// idx ph    flag       flag_bin sample_data_index pitch(for-unvoiced) @n
/// 32: S*    241         11110001 1 0x1e @n
/// 33: SH    226         11100010 2 0x1c @n
/// 34: F*    211         11010011 3 0x1a @n
/// 35: TH    187         10111011 3 0x17 @n
/// 36: /H    124         01111100 4 0x0f @n
/// 37: /X    149         10010101 5 0x12 @n
/// 38: Z*    1           00000001 1 0x00 @n
/// 39: ZH    2           00000010 2 0x00 @n
/// 40: V*    3           00000011 3 0x00 @n
/// 41: DH    3           00000011 3 0x00 @n
/// 43: **    114         01110010 2 0x0e @n
/// 45: **    2           00000010 2 0x00 @n
/// 67: **    27          00011011 3 0x03 @n
/// 70: **    25          00011001 1 0x03 @n
///
unsigned char sampledConsonantFlags[] =
{
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0xF1 , 0xE2 , 0xD3 , 0xBB , 0x7C , 0x95 , 1 , 2 ,
    3 , 3 , 0 , 0x72 , 0 , 2 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0 ,
    0 , 0 , 0 , 0x1B , 0 , 0 , 0x19 , 0 ,
    0 , 0 , 0 , 0 , 0 , 0 , 0 , 0
};



/// @}

